# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-21 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighbourhood_name', models.CharField(max_length=30)),
                ('neighbourhood_location', models.CharField(blank=True, choices=[('Nairobi', 'Nairobi'), ('Nakuru', 'Nakuru'), ('Mombasa', 'Mombasa'), ('Machakos', 'Machakos'), ('Kisumu', 'Kisumu'), ('Eldoret', 'Eldoret'), ('Malindi', 'Malindi'), ('Diani', 'Diani'), ('Naivasha', 'Naivasha'), ('Kiambu', 'Kiambu')], default=0, max_length=200, null=True)),
                ('neighbourhood_count', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
